/* One private learning-review payload for downloads and the optional Drive mirror.
 * This is not the full game backup. Connection settings and credentials are excluded. */
(function(root){
'use strict';
const L=typeof module==='object'&&module.exports?require('./learning.js'):root.HanaLearning;
const course=()=>typeof module==='object'&&module.exports?require('./course.js'):root.HanaCourse;
const eventKeys=['id','session','skill','year','tier','at','updatedAt','independent','correct','manual','lessonHelp','hints','tries','revealed','elapsedMs','activeMs','signature','question','answer','answerDisplay','money','confidence','obstacle','phase','reviewGapMs','form','family','bankRevision','repeated','course','sourcePaper','sourceQuestion','sourcePage','sourceId'];
const str=v=>typeof v==='string'?v.slice(0,4000):v;
function pick(o,keys){const v={};for(const k of keys)if(['string','number','boolean'].includes(typeof o[k])||o[k]===null)v[k]=str(o[k]);return v;}
function sanitizeEvent(e){const v=pick(e,eventKeys);v.independent=L.independent(e);v.notes={};for(const k of ['understand','connect','solve','verify'])if(typeof e.notes?.[k]==='string')v.notes[k]=e.notes[k].slice(0,2000);
 v.strokes=(Array.isArray(e.strokes)?e.strokes:[]).slice(0,100).map(s=>(Array.isArray(s)?s:[]).slice(0,1000).filter(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite)).map(p=>p.map(n=>Math.max(0,Math.min(1,n)))));
 if(Array.isArray(e.attempts))v.attempts=e.attempts.slice(0,30).map(a=>pick(a,['id','at','response','display','correct','feedback']));return v;
}
function zone(tz){try{new Intl.DateTimeFormat('en',{timeZone:tz}).format(0);return tz||Intl.DateTimeFormat().resolvedOptions().timeZone;}catch{return 'UTC';}}
function day(at,tz){const p=new Intl.DateTimeFormat('en-CA',{timeZone:zone(tz),year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(at);const get=t=>p.find(x=>x.type===t).value;return `${get('year')}-${get('month')}-${get('day')}`;}
function category(e){return e.manual?'Grown-up review':e.revealed?'Solution shown':e.confidence==='guess'?'Guessed':e.repeated?'Familiar question':L.independent(e)?'Independent':e.correct===false?'Needs support':'With support';}
function counts(events,checks=[]){const auto=events.filter(e=>!e.manual),measured=events.filter(e=>Number.isFinite(e.activeMs));return {completed:events.length,independent:auto.filter(L.independent).length,supported:auto.filter(e=>!L.independent(e)&&!e.revealed&&e.confidence!=='guess'&&!e.repeated).length,guessed:auto.filter(e=>!e.revealed&&e.confidence==='guess').length,revealed:auto.filter(e=>e.revealed).length,repeated:auto.filter(e=>!e.revealed&&e.confidence!=='guess'&&e.repeated).length,manual:events.length-auto.length,recall:auto.filter(e=>L.independent(e)&&e.phase==='recall'&&e.reviewGapMs>=86400000).length,transfer:auto.filter(e=>L.independent(e)&&e.phase==='transfer').length,activeMs:measured.reduce((n,e)=>n+Math.max(0,e.activeMs),0),unmeasured:events.length-measured.length,lessonChecks:checks.length,lessonChecksPassed:checks.filter(e=>e.passed).length,sessions:new Set(events.map(e=>e.session).filter(Boolean)).size};}
function periods(state,now=Date.now(),tz){const today=day(now,tz),ordinal=d=>Date.parse(d+'T12:00:00Z')/86400000,age=e=>ordinal(today)-ordinal(day(e.at,tz)),s=L.clean(state),window=(min,max)=>counts(s.events.filter(e=>age(e)>=min&&age(e)<=max),s.checks.filter(e=>age(e)>=min&&age(e)<=max));return {today:window(0,0),last7:window(0,6),previous7:window(7,13)};}
function build(state,skills,{now=Date.now(),timeZone}={}){const s=L.clean(state),tz=zone(timeZone);return {app:'Hana learning',schemaVersion:1,appVersion:'h19',exportedAt:now,exportedAtISO:new Date(now).toISOString(),timeZone:tz,limits:['A local snapshot: sync the family devices before comparing reports.','Up to 5,000 completed questions and 2,000 lesson checks are retained. Unfinished questions are not included.','Older builds did not record submitted answers, confidence or active time; missing fields are unknown.','Optional confidence and difficulty reflections are self-reports. Feedback tags are prompts, not diagnoses.','Drawing tasks and written reasoning need a grown-up review. Lesson checks are separate from mastery.','Active minutes are an estimate of visible, recently active practice; speed is never a mastery gate.'],learning:{version:s.version,events:s.events.map(sanitizeEvent),lessons:s.lessons,exposures:s.exposures,checks:s.checks.map(c=>pick(c,['id','skill','at','passed','tries','reason','question','response','answer'])),papers:s.papers.map(p=>({id:p.id,cp:p.cp,title:p.title,at:p.at,elapsedMs:p.elapsedMs,score:p.score,max:p.max,band:p.band,sections:p.sections,topics:p.topics,recs:p.recs,items:(p.items||[]).map(i=>({...pick(i,['id','section','marks','earned','skill','topic','qtext','answer','response','tag','solution','family','bankRevision']),working:sanitizeEvent({strokes:i.working}).strokes}))})),course:(()=>{const K=course();if(!K)return null;try{const st=K.status(s,skills,now);return {settings:st.settings,state:st.state,progressPct:st.progressPct,expectedPct:st.expectedPct,gapWeeks:st.gapWeeks,current:st.current?.id||null,weekSessions:st.weekSessions,advice:st.advice,adjust:st.adjust,repairs:st.repairs.map(r=>r.skill),units:st.units.map(u=>({id:u.id,title:u.title,due:u.due,ready:u.ready,skills:u.skills.length}))};}catch{return null;}})()},periods:periods(s,now,tz),next:[3,4].map(y=>L.recommend(s,skills,y,now)),skills:skills.map(skill=>{const e=L.evidence(s,skill.id,now);return {id:skill.id,name:skill.name,year:skill.year,manual:!!skill.manual,total:e.total,recent:e.recent,independentRecent:e.success,tier:e.tier,status:e.label,due:e.due,reviewAt:e.reviewAt,delayedRecall:e.delayed,applications:e.transfer};})};}
function csv(backup){const cell=v=>'"'+String(v??'').replace(/^[\s]*[=+\-@]/,m=>"'"+m).replace(/"/g,'""')+'"';const rows=[['Date','Skill','Level','Outcome','Phase','Question','Expected answer','First response','Submitted responses','Confidence','Felt tricky','Hints','Retries','Active minutes','Understand','Connect','Solve','Check']];for(const e of backup.learning.events)rows.push([new Date(e.at).toISOString(),e.skill,e.tier,category(e),e.phase||'Unknown',e.question,e.answerDisplay??e.answer,e.attempts?.[0]?.display??e.attempts?.[0]?.response??'Not recorded',e.attempts?.map(a=>a.display??a.response).join(' → ')??'Not recorded',e.confidence||'Unreported',e.obstacle||'',e.hints,e.tries,Number.isFinite(e.activeMs)?(e.activeMs/60000).toFixed(1):'Unknown',...['understand','connect','solve','verify'].map(k=>e.notes?.[k]||'')]);return '\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n');}
const api={build,periods,counts,category,csv,day,zone};if(typeof module==='object'&&module.exports)module.exports=api;else root.HanaReview=api;
})(typeof window==='undefined'?globalThis:window);
