/* Original introductory mini-lessons for every P3/P4 skill in curriculum.js.
 * Text, diagrams and checks are bundled for offline use. Read-aloud uses the
 * device voice; the family's recorded encouragement is kept separately. */
(function(root){
'use strict';
const lessons={};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svg=(label,body,h=170)=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 ${h}" role="img" aria-label="${esc(label)}"><title>${esc(label)}</title>${body}</svg>`;
const text=(x,y,s)=>`<text x="${x}" y="${y}" text-anchor="middle" font-size="17" fill="#352644">${esc(s)}</text>`;
const box=(x,y,w,h,fill='#e8dcf6')=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="3" fill="${fill}" stroke="#7850aa"/>`;
const line=(x,y,a,b,more='')=>`<line x1="${x}" y1="${y}" x2="${a}" y2="${b}" stroke="#7850aa" stroke-width="3" ${more}/>`;
const strip=(parts,filled,label)=>svg(label,Array.from({length:parts},(_,i)=>box(30+i*340/parts,35,340/parts,65,i<filled?'#b6d9c8':'#fff')).join('')+text(200,139,label));
const tiles=(labels,caption)=>svg(caption,labels.map((v,i)=>box(20+i*360/labels.length,30,360/labels.length,65)+text(20+(i+.5)*360/labels.length,70,v)).join('')+text(200,138,caption));
const table=(headers,values,caption)=>`<table class="data-table"><caption>${esc(caption)}</caption><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody><tr>${values.map(x=>`<td>${esc(x)}</td>`).join('')}</tr></tbody></table>`;
const rectangle=(a='8 cm',b='3 cm')=>svg('Rectangle: '+a+' by '+b,box(90,35,220,90)+text(200,24,a)+text(351,86,b)+text(200,158,'Diagram not to scale'));
const angle=svg('A right angle is 90 degrees',line(120,25,120,135)+line(120,135,310,135)+'<path d="M120 111H144V135" fill="none" stroke="#7850aa"/>'+text(212,90,'90°'));
const parallel=svg('Parallel lines stay the same distance apart',line(60,50,340,50)+line(60,115,340,115)+text(200,151,'Same direction, same gap'));
const lshape=svg('Large rectangle 8 by 6. A 3 by 2 corner is removed.','<path d="M65 35H315V90H220V145H65Z" fill="#e8dcf6" stroke="#7850aa" stroke-width="2"/>'+text(190,25,'8 cm')+text(30,95,'6 cm')+text(270,115,'3 cm')+text(260,147,'2 cm'));
const mirror=svg('Matching corners are equally far from a mirror line',line(200,15,200,145,'stroke-dasharray="6 5"')+'<path d="M170 35H110V115H170Z M230 35H290V115H230Z" fill="#e8dcf6" stroke="#7850aa"/>'+text(200,165,'Count squares from the mirror line'));
const net=svg('A cube net has six equal squares',[[0,1],[1,1],[2,1],[3,1],[1,0],[1,2]].map(([x,y])=>box(100+x*42,15+y*42,42,42)).join('')+text(200,162,'6 equal square faces'));
const chart=svg('Books borrowed: Monday 4, Tuesday 8, Wednesday 6',[0,2,4,6,8].map(n=>line(65,135-n*12,350,135-n*12,'stroke-width="1" stroke="#d9d0e4"')+text(40,141-n*12,n)).join('')+[4,8,6].map((n,i)=>box(95+i*85,135-n*12,40,n*12)+text(115+i*85,160,['Mon','Tue','Wed'][i])).join(''));
const linechart=svg('Books borrowed: Monday 4, Tuesday 8, Wednesday 6',[0,2,4,6,8].map(n=>line(65,135-n*12,350,135-n*12,'stroke-width="1" stroke="#d9d0e4"')+text(40,141-n*12,n)).join('')+'<polyline points="115,87 200,39 285,63" fill="none" stroke="#7850aa" stroke-width="3"/>'+[4,8,6].map((n,i)=>`<circle cx="${115+i*85}" cy="${135-n*12}" r="5" fill="#7850aa"/>`+text(115+i*85,160,['Mon','Tue','Wed'][i])).join(''));
const pie=svg('Half choose reading; a quarter each choose drawing and swimming','<path d="M115 85V15A70 70 0 0 1 115 155Z" fill="#bea4df"/><path d="M115 85V155A70 70 0 0 1 45 85Z" fill="#a7d7c0"/><path d="M115 85H45A70 70 0 0 1 115 15Z" fill="#f3cc84"/>'+text(284,47,'Reading: 1/2')+text(284,87,'Drawing: 1/4')+text(284,127,'Swimming: 1/4'));
function add(id,goal,idea,visual,example,steps,question,options,answer,explanation){
 lessons[id]={id,goal,idea,visual,example,steps,check:{question,options,answer,explanation}};
}
for(const year of [3,4]){
 const p='p'+year,n=year===3?'4 308':'43 208';
 add(p+'-place','Read a number one place at a time.','A digit gets its value from its position. Each place is ten times the place to its right. Zero holds an empty place. We can also write numbers in words.',year===3?table(['Thousands','Hundreds','Tens','Ones'],[4,3,0,8],n):table(['Ten thousands','Thousands','Hundreds','Tens','Ones'],[4,3,2,0,8],n),`What is the value of 3 in ${n}?`,year===3?['3 is in the hundreds place.','3 hundreds = 3 × 100 = 300.','4 308 is four thousand three hundred and eight.']:['3 is in the thousands place.','3 thousands = 3 × 1 000 = 3 000.','43 208 is forty-three thousand two hundred and eight.'],'What is the value of the 6 in 6 205?',['6','600','6 000'],'6 000','6 is in the thousands place: 6 × 1 000 = 6 000.');
 add(p+'-patterns','Compare numbers and spot a constant change.','Compare from the largest place. If those digits match, move one place to the right. In a number pattern, test the same change between every pair of neighbours.',tiles(year===3?['2 150','2 250','2 350','?']:['21 500','22 500','23 500','?'],year===3?'Add 100 each time':'Add 1 000 each time'),'Which is greater: 4 305 or 4 350?',['Both have 4 thousands and 3 hundreds.','Compare the tens: 0 tens is less than 5 tens.','4 350 is greater. For the pattern above, add the same step again.'],'Complete: 3 200, 3 300, 3 400, __.',['3 410','3 500','4 400'],'3 500','Each number is 100 more than the number before it.');
 add(p+'-remainder','Share equally and name what is left over.','The quotient is the number in each equal group. The remainder is what cannot be shared into another whole round. It must be smaller than the divisor.',tiles(['6','6','6','5 left'],'23 = 3 × 6 + 5'),'Find 23 ÷ 6.',['3 full groups of 6 use 18.','23 − 18 = 5 are left.','23 ÷ 6 = 3 R 5. Check: 6 × 3 + 5 = 23.'],'What is 29 ÷ 4?',['6 R 5','7 R 1','8 R 1'],'7 R 1','4 × 7 = 28 and 29 − 28 = 1. The remainder 1 is smaller than 4.');
}
add('p3-addsub','Keep ones with ones and regroup when needed.','Addition joins amounts. Subtraction finds a difference or what is left. Align place values. Exchange 1 ten for 10 ones when you need to subtract more ones than you have.',table(['Hundreds','Tens','Ones'],[2,4,3],'243 = 2 hundreds + 3 tens + 13 ones'),'Work out 243 − 128.',['3 ones cannot take away 8 ones. Exchange 1 ten: 4 tens becomes 3 tens, and 3 ones becomes 13 ones.','13 − 8 = 5 ones; 3 − 2 = 1 ten; 2 − 1 = 1 hundred.','The answer is 115. Check: 115 + 128 = 243.'],'What is 152 − 27?',['135','125','145'],'125','Exchange a ten: 12 − 7 = 5 ones, 4 − 2 = 2 tens, with 1 hundred left.');
add('p3-tables','Build the 6, 7, 8 and 9 times tables from known facts.','Multiplication counts equal groups. Division uses the same facts in reverse. You can split a tricky fact into easier groups.',tiles(['5 × 7 = 35','1 × 7 = 7'],'6 × 7 = 35 + 7'),'Find 6 × 7, then 42 ÷ 6.',['5 groups of 7 make 35.','One more group of 7 makes 42. So 6 × 7 = 42.','42 shared into 6 equal groups gives 7 in each group.'],'What is 8 × 6?',['42','48','54'],'48','5 × 6 = 30 and 3 × 6 = 18. Together they make 48.');
add('p3-muldiv','Split a larger number into place values.','Multiply each place, then combine. When dividing, share the largest place first and regroup any leftover into the next place.',tiles(['100 × 3','20 × 3','4 × 3'],'124 × 3 = 300 + 60 + 12'),'Work out 124 × 3.',['Split 124 into 100 + 20 + 4.','Multiply by 3: 300 + 60 + 12 = 372.','Check with division: 372 ÷ 3 = 124.'],'What is 132 × 2?',['264','244','262'],'264','Double each part: 200 + 60 + 4 = 264.');
add('p3-equivalent','Rename a fraction without changing its size.','Equivalent fractions show the same share of equal-sized wholes. Multiply or divide the numerator and denominator by the same number. The simplest form has no common factor greater than 1.',strip(6,4,'2/3 = 4/6'),'Why is 2/3 equal to 4/6?',['Split each third into 2 equal parts. The whole now has 6 parts.','The 2 shaded thirds become 4 shaded sixths.','Multiply top and bottom by 2: 2/3 = 4/6. Divide both by 2 to simplify.'],'Which fraction equals 2/4?',['1/4','1/2','2/3'],'1/2','Divide the numerator and denominator of 2/4 by 2.');
add('p3-fraccompare','Compare equal-sized pieces from equal-sized wholes.','Fractions can only be compared fairly when their wholes are the same size. Rename unlike fractions with a shared denominator, then compare the numerators.',strip(6,4,'2/3 = 4/6, which is greater than 3/6'),'Compare 1/2 and 2/3.',['Rename both in sixths: 1/2 = 3/6 and 2/3 = 4/6.','3 sixths is smaller than 4 sixths.','So 1/2 < 2/3.'],'Compare 3/4 and 1/2.',['3/4 < 1/2','3/4 = 1/2','3/4 > 1/2'],'3/4 > 1/2','1/2 = 2/4. Three quarters is greater than two quarters.');
add('p3-fracops','Add or subtract pieces of the same size.','For related denominators, one denominator is a multiple of the other. Rename the fractions using the larger denominator. Add or subtract only the numerators; the size of each piece stays the same.',strip(4,3,'1/2 + 1/4 = 2/4 + 1/4'),'Find 1/2 + 1/4.',['Rename 1/2 as 2/4.','2 quarters + 1 quarter = 3 quarters.','The answer is 3/4, not 2/6.'],'What is 3/4 − 1/2?',['1/4','2/2','2/4'],'1/4','Rename 1/2 as 2/4, then subtract: 3/4 − 2/4 = 1/4.');
add('p3-money','Work with dollars and cents together.','One dollar is 100 cents. Use two digits for cents and align decimal points. Add prices to find a total. Subtract the total from the payment to find change.',table(['Payment','Cost','Change'],['$5.00','$2.35','$2.65'],'Payment = cost + change'),'Find the change from $5 for a $2.35 snack.',['Convert to cents: 500 − 235 = 265 cents.','265 cents = $2.65.','Check: $2.35 + $2.65 = $5.00.'],'What is $1.20 + $2.45?',['$3.65','$3.25','$2.65'],'$3.65','Add dollars and cents in their places: 120 + 245 = 365 cents.');
add('p3-measure','Convert larger units into equal smaller units.','1 km = 1 000 m; 1 m = 100 cm; 1 kg = 1 000 g; 1 litre = 1 000 ml. Multiply to make smaller units. Group smaller units to make larger units.',tiles(['2 000 g','350 g'],'2 kg 350 g = 2 350 g'),'Convert 3 m 25 cm to centimetres.',['3 m = 3 × 100 cm = 300 cm.','Add the remaining 25 cm: 300 + 25 = 325 cm.','In reverse, 325 cm makes 3 full metres and 25 cm.'],'How many grams are in 1 kg 80 g?',['180 g','1 080 g','1 800 g'],'1 080 g','1 kilogram is 1 000 grams. Add the remaining 80 grams.');
add('p3-time','Use groups of 60 for time.','60 seconds make 1 minute; 60 minutes make 1 hour. The 24-hour clock runs from 0000 at midnight. After noon, add 12 to hours 1 to 11. Noon is 1200; midnight is 0000.',tiles(['14:45 → 15:00','15:00 → 15:20'],'15 minutes + 20 minutes = 35 minutes'),'A trip starts at 1445 and ends at 1520. How long is it?',['Count 15 minutes to 1500, then 20 minutes to 1520.','15 + 20 = 35 minutes. To find a start time, count backwards instead.','For seconds: 2 min 10 s = 2 × 60 + 10 = 130 s.'],'Write 3:15 pm in 24-hour time.',['0315','1515','1315'],'1515','3 pm is 15 hours. The minutes stay at 15.');
add('p3-area','Tell the inside from the boundary.','Area counts square units covering a flat surface. Rectangle area = length × breadth. Perimeter is the total length around the outside; add all boundary edges, including every turn in a rectilinear shape.',rectangle(),'Find the area and perimeter of an 8 cm by 3 cm rectangle.',['Area: 8 × 3 = 24 cm².','Perimeter: 8 + 3 + 8 + 3 = 22 cm.','Area uses square units; perimeter uses length units.'],'A 5 cm by 2 cm rectangle has what perimeter?',['10 cm','14 cm','7 cm'],'14 cm','Walk around all four sides: 5 + 2 + 5 + 2 = 14 cm.');
add('p3-angles','Compare a turn with a square corner.','An angle is the amount of turn between two rays meeting at a point. A right angle matches a square corner. Longer arms do not make an angle larger.',angle,'How can you check whether an angle is smaller than a right angle?',['Place a paper corner with its point on the vertex.','Line up one edge with one arm of the angle.','If the other arm is inside the square corner, the angle is smaller.'],'Does making the arms longer change the angle?',['Yes, it grows','No, the turn stays the same'],'No, the turn stays the same','The angle depends on the turn between the arms, not their lengths.');
add('p3-lines','Recognise parallel and perpendicular lines in any direction.','Parallel straight lines stay the same distance apart and never meet, even if extended. Perpendicular lines meet at a right angle. Slanted lines can be parallel or perpendicular too.',parallel,'Are opposite edges of a rectangle parallel?',['The opposite edges run in the same direction.','Their gap stays the same: they are parallel.','Neighbouring edges meet at a square corner: they are perpendicular.'],'Two lines meet at a square corner. They are…',['Parallel','Perpendicular','Neither'],'Perpendicular','Perpendicular lines meet at a right angle.');
add('p3-bars','Read the scale before reading a bar.','A bar graph compares amounts. Read the labels and find the value of each scale interval. Bars start at the baseline; their heights show amounts.',chart,'How many more books were borrowed on Tuesday than Monday?',['Each scale interval is 2 books. Monday shows 4 and Tuesday shows 8.','Subtract: 8 − 4 = 4.','Tuesday has 4 more books. Add values if a question asks for a total.'],'Using the graph, how many books were borrowed on Wednesday?',['3','6','8'],'6','The bar reaches 6 on the vertical scale, not just the third interval.');
add('p3-story','Plan two steps before calculating.','Read what each number means. Decide which quantity you need first, then use it to answer the question. A bar model can show equal groups and an amount taken away.',tiles(['8','8','8','8'],'4 packs of 8 stickers = 32'),'Hana has 4 packs of 8 stickers and gives away 7. How many remain?',['First find the total: 4 × 8 = 32.','Then subtract the stickers given away: 32 − 7 = 25.','Check: 25 + 7 = 32, which matches the 4 packs.'],'3 boxes hold 6 pencils each. 5 pencils are used. How many are left?',['13','23','8'],'13','First 3 × 6 = 18. Then 18 − 5 = 13.');
add('p4-round','Choose the nearer multiple.','Rounding gives an approximate number. Look one place to the right of the place being rounded. A digit of 5 or more rounds up; a digit below 5 rounds down.',tiles(['4 300','4 368','4 400'],'4 368 is nearer to 4 400'),'Round 4 368 to the nearest hundred.',['The hundreds digit is 3. Look at the tens digit, 6.','6 is at least 5, so round up to 4 400.','Write 4 368 ≈ 4 400. For the nearest ten, inspect the ones digit instead.'],'Round 2 749 to the nearest hundred.',['2 700','2 800','2 750'],'2 700','The tens digit is 4, below 5, so round down to 2 700.');
add('p4-factors','Separate factors from multiples.','A factor divides a number exactly. A multiple is the result of multiplying a number by a whole number. Common factors or multiples belong to both numbers.',table(['Number','Factors'],['12','1, 2, 3, 4, 6, 12'],'Factor pairs of 12: 1 × 12, 2 × 6, 3 × 4'),'Find a common factor and the smallest positive common multiple of 4 and 6.',['Factors shared by 4 and 6 are 1 and 2.','Multiples of 4: 4, 8, 12, 16… Multiples of 6: 6, 12, 18…','The first positive shared multiple is 12.'],'Which is a common factor of 12 and 18?',['4','6','9'],'6','12 ÷ 6 = 2 and 18 ÷ 6 = 3, both with no remainder.');
add('p4-multiply','Multiply by the ones and the tens separately.','For a two-digit multiplier, split it into tens and ones. Multiply both parts and add the partial products. A tens digit stands for tens, not ones.',tiles(['23 × 10 = 230','23 × 4 = 92'],'23 × 14 = 230 + 92'),'Work out 23 × 14.',['14 = 10 + 4.','23 × 10 = 230 and 23 × 4 = 92.','230 + 92 = 322. Estimate: 20 × 15 = 300, so 322 is sensible.'],'What is 32 × 12?',['96','384','324'],'384','32 × 10 = 320 and 32 × 2 = 64. Add to get 384.');
add('p4-divide','Share each place and regroup the remainder.','Divide from the largest place. A leftover hundred becomes 10 tens; a leftover ten becomes 10 ones. Write zero in the quotient when no whole group fits at that place.',table(['Thousands','Hundreds','Tens','Ones'],[1,2,4,8],'1 248 ÷ 4'),'Work out 1 248 ÷ 4.',['1 thousand is too small to share as thousands. Regroup as 12 hundreds.','12 hundreds ÷ 4 = 3 hundreds; 4 tens ÷ 4 = 1 ten.','8 ones ÷ 4 = 2 ones. Answer: 312. Check: 312 × 4 = 1 248.'],'What is 840 ÷ 4?',['21','210','240'],'210','8 hundreds ÷ 4 = 2 hundreds and 4 tens ÷ 4 = 1 ten. Keep the ones place zero.');
add('p4-mixed','Rename whole units and fractional parts.','An improper fraction has a numerator at least as large as its denominator. A mixed number contains a whole number and a proper fraction. Group the pieces into wholes.',tiles(['4/4','4/4','3/4'],'2 3/4 = 11/4'),'Write 2 3/4 as an improper fraction.',['Each whole contains 4 quarters. Two wholes contain 8 quarters.','Add the 3 extra quarters: 8 + 3 = 11.','So 2 3/4 = 11/4. In reverse, 11 ÷ 4 = 2 R 3.'],'Write 7/3 as a mixed number.',['1 1/3','2 1/3','3 1/3'],'2 1/3','7 thirds make 2 whole groups of 3, with 1 third left.');
add('p4-fracset','Share a set, then choose the required groups.','The denominator tells how many equal groups to make. The numerator tells how many groups to take. To find the whole from a known fraction, first find one group.',tiles(['6','6','6','6'],'3/4 of 24: take 3 groups of 6'),'Find 3/4 of 24 beads.',['24 ÷ 4 = 6 beads in one group.','Take 3 groups: 6 × 3 = 18.','The other group contains 6 beads. 18 + 6 = 24.'],'What is 2/3 of 18?',['6','12','9'],'12','18 ÷ 3 = 6, then 6 × 2 = 12.');
add('p4-fracops','Find a common denominator before calculating.','For unlike fractions, choose a denominator that is a multiple of both denominators. Rename both fractions, combine the numerators, then simplify. The answer may be greater than one.',strip(6,5,'1/2 + 1/3 = 3/6 + 2/6'),'Find 1/2 + 1/3.',['6 is a multiple of both 2 and 3.','1/2 = 3/6 and 1/3 = 2/6.','3/6 + 2/6 = 5/6. Subtraction uses the same renaming step.'],'What is 3/4 − 1/3?',['2/1','5/12','2/12'],'5/12','Use twelfths: 9/12 − 4/12 = 5/12.');
add('p4-decimalplace','Read and compare decimal places carefully.','To the right of the decimal point are tenths, hundredths and thousandths. Compare from left to right. Zeros at the end do not change a decimal’s value. To round, inspect the next place.',table(['Ones','Tenths','Hundredths','Thousandths'],[2,3,4,7],'2.347'),'Round 2.347 to two decimal places.',['Two decimal places means stop at hundredths: 2.34.','Inspect the thousandths digit, 7.','7 is at least 5, so round the hundredths up: 2.35.'],'Which is greater: 0.6 or 0.58?',['0.6','0.58','They are equal'],'0.6','0.6 = 0.60. Sixty hundredths is greater than fifty-eight hundredths.');
add('p4-decimalfraction','Connect tenths and hundredths to fractions.','A decimal is another way to write a fraction. One tenth is 0.1 and one hundredth is 0.01. Make an equivalent fraction with denominator 10 or 100 to convert.',strip(4,3,'3/4 = 75/100 = 0.75'),'Write 3/4 as a decimal.',['Multiply numerator and denominator by 25.','3/4 = 75/100 = 0.75.','To reverse it, write 75/100 and divide both numbers by 25.'],'Which decimal equals 2/5?',['0.2','0.4','0.25'],'0.4','2/5 = 4/10, which is 0.4.');
add('p4-decimalops','Calculate with place values on both sides of the point.','For addition and subtraction, align decimal points. For multiplication or division by a whole number, calculate with tenths or hundredths and keep track of their value.',table(['Number','In hundredths'],['2.35','235 hundredths'],'3.00 = 300 hundredths'),'Work out 2.35 + 0.8.',['Write 0.8 as 0.80 so the places match.','235 hundredths + 80 hundredths = 315 hundredths.','Answer: 3.15. Similarly, 1.25 × 3 = 3.75 and 3.75 ÷ 3 = 1.25.'],'What is 4.2 − 1.35?',['3.15','2.85','2.95'],'2.85','Write 4.20 − 1.35. In hundredths, 420 − 135 = 285.');
add('p4-decimalquotient','Keep dividing far enough to round the answer.','A remainder can be regrouped into tenths, then hundredths and thousandths. For a rounded answer, find one extra decimal digit before rounding.',tiles(['5 ÷ 4 = 1.25','Nearest tenth: 1.3'],'Keep an extra digit before rounding'),'Round 5 ÷ 4 to one decimal place.',['4 goes into 5 once, with 1 left.','Regroup: 10 tenths ÷ 4 gives 2 tenths with 2 tenths left; 20 hundredths ÷ 4 gives 5 hundredths.','1.25 rounds to 1.3 because the hundredths digit is 5.'],'Round 10 ÷ 3 to two decimal places.',['3.30','3.33','3.34'],'3.33','10 ÷ 3 = 3.333… The third decimal digit is 3, so the hundredths stay unchanged.');
add('p4-dimension','Undo an area or perimeter calculation.','Rectangle area = length × breadth, so divide by the known side to find the missing one. Half a rectangle’s perimeter is length + breadth. A square has four equal sides.',rectangle('8 cm','? cm'),'A rectangle has area 24 cm² and length 8 cm. Find its breadth.',['24 ÷ 8 = 3 cm.','Check: 8 × 3 = 24 cm².','If its perimeter were given as 22 cm, calculate 22 ÷ 2 − 8 = 3 cm instead.'],'A square has perimeter 28 cm. How long is each side?',['7 cm','14 cm','4 cm'],'7 cm','Divide the perimeter equally among the four sides: 28 ÷ 4 = 7.');
add('p4-composite','Split a complicated shape into rectangles.','For area, add non-overlapping rectangles or subtract a missing rectangle from a large one. For perimeter, trace only the outside boundary and work out missing lengths.',lshape,'Find the area and perimeter of this L shape.',['Large rectangle: 8 × 6 = 48 cm². Missing corner: 3 × 2 = 6 cm².','Area: 48 − 6 = 42 cm².','Missing outside sides: 6 − 2 = 4 cm and 8 − 3 = 5 cm. Perimeter: 8 + 4 + 3 + 2 + 5 + 6 = 28 cm.'],'A 10 by 5 rectangle has a 2 by 2 corner removed. What area remains?',['46 cm²','48 cm²','54 cm²'],'46 cm²','Subtract the missing area: 10 × 5 − 2 × 2 = 50 − 4 = 46 cm².');
add('p4-angles','Name the vertex and read a protractor from zero.','In angle ABC, the middle letter B names the vertex. Put the protractor’s centre on B and its baseline along one ray. Use the scale starting at zero on that ray.',angle,'How do you measure an angle that opens 60° from the right-hand baseline?',['Put the centre at the vertex. Align the baseline with the lower ray.','Start at 0 on the right and follow that scale to the other ray.','Read 60°, not 120°. Check that the opening is smaller than a right angle.'],'Which letter is the vertex of angle PQR?',['P','Q','R'],'Q','The middle letter names the vertex: Q.');
add('p4-properties','Use properties that stay true when a shape turns.','Rectangles and squares have four right angles and two pairs of parallel opposite sides. Opposite rectangle sides are equal. A square also has all four sides equal. Rotation does not change these properties.',rectangle(),'Must a rectangle have four equal sides?',['A rectangle needs four right angles and equal opposite sides.','An 8 cm by 3 cm rectangle meets these rules but its four sides are not all equal.','A square meets the rectangle rules and has four equal sides too.'],'Which must be true for every square?',['All four sides are equal','Only two angles are right angles','Opposite sides meet'],'All four sides are equal','A square has four equal sides, four right angles and parallel opposite sides.');
add('p4-symmetry','Find a fold that makes two halves match.','A line of symmetry divides a figure into halves that match exactly when folded. A line through the middle is not always a line of symmetry: matching lengths and corners matter.',mirror,'How many lines of symmetry does a non-square rectangle have?',['A vertical line through the centre matches left and right halves.','A horizontal line through the centre matches top and bottom halves.','The diagonals do not match the halves. There are 2 lines. A square has 4.'],'How many lines of symmetry does a square have?',['2','4','8'],'4','Two lines join opposite side midpoints and two follow the diagonals.');
add('p4-nets','Imagine flat faces folding to make a solid.','A net is an arrangement of faces that folds into a solid without overlaps. Match the face shapes and their shared edges. Drawings can show hidden edges with dotted lines.',net,'How can you recognise a cube net?',['A cube needs 6 equal square faces.','The squares must be joined so they can fold without faces overlapping.','A cuboid has rectangular faces; a triangular prism has 2 triangular and 3 rectangular faces. A square pyramid has 1 square and 4 triangles.'],'Which faces make a triangular prism?',['6 squares','2 triangles and 3 rectangles','1 square and 4 triangles'],'2 triangles and 3 rectangles','The two triangles are matching ends, joined by three rectangular side faces.');
add('p4-tables','Use headings to read values and totals.','A table organises data into rows and columns. Read both headings to know what a value means. A total includes every part, so a missing part equals the total minus all known parts.',table(['Mon','Tue','Wed','Total'],[12,'?',15,40],'Books borrowed'),'How many books were borrowed on Tuesday?',['The total for all three days is 40.','Known books: 12 + 15 = 27.','Missing books: 40 − 27 = 13. Check: 12 + 13 + 15 = 40.'],'A total of 35 includes 9, 12 and one missing amount. What is missing?',['14','16','26'],'14','35 − (9 + 12) = 35 − 21 = 14.');
add('p4-linegraphs','Follow how an amount changes over time.','Read the horizontal and vertical labels and the scale. Each point gives a value at a time. A rising line shows an increase; a falling line shows a decrease.',linechart,'What happened from Tuesday to Wednesday?',['Tuesday shows 8 books; Wednesday shows 6.','The line falls, so the amount decreases.','The decrease is 8 − 6 = 2 books. Do not read the slope as the number of books.'],'How much did the number increase from Monday to Tuesday?',['2 books','4 books','8 books'],'4 books','Monday is 4 and Tuesday is 8. The increase is 8 − 4 = 4 books.');
add('p4-piecharts','Connect each sector with its share of the whole.','A pie chart shows parts of one whole. All sectors together represent the total. Use halves or quarters when those shares are given. No percentage or angle calculation is needed here.',pie,'24 children chose one favourite activity each. How many chose drawing?',['Drawing is one quarter of the whole circle.','24 ÷ 4 = 6 children.','Reading is one half: 12 children. Swimming is the other quarter: 6. Check: 12 + 6 + 6 = 24.'],'With 20 children in total, how many chose reading?',['5','10','15'],'10','Reading takes half the circle, so 20 ÷ 2 = 10 children.');
add('p3-drawlines','Use tools to draw straight lines accurately.','Use a ruler for straight lines and a square corner to check right angles. Parallel lines must keep the same gap. Practise on paper and ask a grown-up to check.',parallel,'Draw a line perpendicular to another line.',['Draw one straight line with a ruler.','Place a square corner with one edge on your line.','Draw along the other edge. Check that the two lines meet at a right angle.'],'Which tool helps check a perpendicular intersection?',['A square corner','A circular lid','A curved edge'],'A square corner','A square corner checks a right angle. Drawing tasks are reviewed by a grown-up.');
add('p4-construct','Measure on paper with a ruler and protractor.','Screen centimetres depend on the device. Use paper tools for accurate lengths and angles. Build a rectangle using perpendicular sides; make every side equal for a square. A solid drawing shows how faces join.',angle,'Draw an angle of 60°, then a 4 cm by 2 cm rectangle.',['Angle: draw a ray, centre the protractor at its endpoint, start at 0 and mark 60°. Join the endpoint to the mark.','Rectangle: draw 4 cm, make right angles at both ends, mark 2 cm on each new side and join the final corners.','For a solid, join corresponding corners of the faces. Show hidden edges with dotted lines. Ask a grown-up to check.'],'Where should the centre of a protractor go?',['At the vertex','At the end of the longest arm','Anywhere on the baseline'],'At the vertex','Centre the protractor at the vertex and align its baseline with one ray.');
add('p4-drawsymmetry','Reflect each corner the same distance across the line.','A reflection is a mirror image. Matching points lie on opposite sides of the mirror line at equal perpendicular distances. Points on the mirror line stay in place.',mirror,'Reflect a corner 3 grid squares to the left of a vertical mirror line.',['Stay in the same row. Count 3 squares to the right of the line.','Mark the matching corner there. Repeat for each corner.','Join the reflected corners in the same order and check by imagining a fold.'],'A point is 2 squares left of a vertical mirror line. Where is its reflection?',['2 squares right, same row','2 squares right, one row up','On the mirror line'],'2 squares right, same row','Keep the same distance on the other side, measured straight across the line.');
const api={lessons,get:id=>lessons[id]};if(typeof module==='object'&&module.exports)module.exports=api;else root.HanaLessons=api;
})(typeof window==='undefined'?globalThis:window);
