/* Checkpoint papers: mixed-topic, exam-style assessments built from the course.
 * Format calibrated against 2025 Singapore school papers (P3 end-of-year, P4
 * weighted assessments 1 and 2): about 35 marks in 40–45 minutes for a weighted
 * assessment, with Section A multiple choice (1–2 marks), Section B short
 * answers (2 marks) and Section C word problems (3–5 marks) where working is
 * shown. All questions are generated by this app; no paper is reproduced.
 * Pure functions (no DOM). Results feed course.js through learning.papers. */
(function(root){
'use strict';
const node=typeof module==='object'&&module.exports;
const C=node?require('./curriculum.js'):root.HanaCurriculum;
const K=node?require('./course.js'):root.HanaCourse;
const FORMATS={
 short:{A:[1,1,2,2,2],B:8,C:[3,4,4],minutes:45},           // 8 + 16 + 11 = 35 marks
 full:{A:[1,1,1,1,1,2,2,2,2,2],B:10,C:[3,3,4,4,5],minutes:70} // 15 + 20 + 19 = 54 marks
};
const shuffle=(a,r)=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const uid=r=>Date.now().toString(36)+Math.floor(r()*1e9).toString(36);
function skillsFor(units,skills){return K.UNITS.filter(u=>units.includes(u.id)).flatMap(u=>u.skills).map(id=>skills.find(s=>s.id===id)).filter(s=>s&&!s.manual);}
// Turn any auto-marked question into four options with plausible slips.
function toChoice(spec,r){
 if(spec.kind==='choice'&&spec.choices.length>=3)return spec;
 const fmtv=v=>spec.money?'$'+(v/100).toFixed(2):spec.dec?String(Math.round(v*1000)/1000):String(v);
 let correct,wrong=[];
 if(spec.kind==='key'){
  const a=spec.ans;correct=fmtv(a);
  const steps=spec.money?[100,10,1000,50]:spec.dec?[.1,.01,1,a*9]:[1,10,100,a>=1000?1000:2];
  for(const s of steps){wrong.push(fmtv(a+s));if(a-s>0)wrong.push(fmtv(a-s));}
  if(!spec.dec&&!spec.money&&a>=10){const d=String(a).split('');if(d.length>1&&d.at(-1)!==d.at(-2)){[d[d.length-1],d[d.length-2]]=[d[d.length-2],d[d.length-1]];wrong.push(d.join(''));}}
 }else if(spec.kind==='parts'){
  const e=spec.expect;correct=spec.ansText;
  if(spec.layout==='fraction'||spec.layout==='mixed'){for(const [n,d] of [[e.N+1,e.D],[Math.max(1,e.N-1),e.D],[e.N,e.D+1],[e.D,e.N],[e.N+e.D,e.D]])if(n>0&&d>0&&n*e.D!==e.N*d)wrong.push(C.mixedText(n,d));}
  if(spec.layout==='units')wrong.push(`${e.a+1} ${e.big} ${e.b} ${e.small}`,`${e.a} ${e.big} ${e.b+1} ${e.small}`,`${e.a} ${e.big} ${(e.b*10)%e.k} ${e.small}`,e.a>1?`${e.a-1} ${e.big} ${e.b} ${e.small}`:`${e.a+2} ${e.big} ${e.b} ${e.small}`);
  if(spec.layout==='remainder')wrong.push(`${e.q+1} R ${e.r}`,`${e.q} R ${(e.r+1)%e.divisor}`,`${Math.max(0,e.q-1)} R ${e.r}`,`${e.q*10} R ${e.r}`);
  if(spec.layout==='clock'){const c=m=>{m=((m%1440)+1440)%1440;return String(Math.floor(m/60)).padStart(2,'0')+String(m%60).padStart(2,'0');},t=e.h*60+e.m;wrong.push(c(t+60),c(t-60),c(t+10),c(t+720));}
 }else return null;
 const opts=[...new Set(wrong.filter(w=>w!==correct))].slice(0,3);
 if(opts.length<3)return null;
 const choices=shuffle([correct,...opts],r).map(v=>({v,t:v}));
 return {...spec,kind:'choice',ans:correct,choices,original:spec.kind};
}
function build(cpId,skills,{random=Math.random,now=Date.now(),units=null,title=null,size=null}={}){
 const cp=K.CHECKPOINTS.find(c=>c.id===cpId)||{id:cpId||'practice',title:title||'Practice checkpoint',units:units||[],review:[],size:size||'short',style:'Mixed practice'};
 const fmt=FORMATS[size||cp.size]||FORMATS.short,r=random;
 const main=skillsFor(units||cp.units,skills),review=skillsFor(cp.review||[],skills);
 const calc=main.filter(s=>!s.wordProblem),calcReview=review.filter(s=>!s.wordProblem);
 const wpMain=main.filter(s=>s.wordProblem),wpReview=review.filter(s=>s.wordProblem);
 // Spread questions evenly over skills before repeating any.
 const draw=(pool,n)=>{const out=[];let bag=[];while(out.length<n&&pool.length){if(!bag.length)bag=shuffle(pool,r);out.push(bag.pop());}return out;};
 // About a quarter of a P4 checkpoint revisits earlier units, as school papers do.
 const mix=(mainPool,reviewPool,n)=>{const k=reviewPool.length?Math.round(n*.25):0;return shuffle([...draw(mainPool.length?mainPool:reviewPool,n-k),...draw(reviewPool,k)],r);};
 const items=[];let no=0;
 for(const [i,s] of mix(calc,calcReview,fmt.A.length).entries()){
  let spec=null;for(let k=0;k<12&&!spec;k++)spec=toChoice(C.generate(s.id,1+Math.floor(r()*2),r),r);
  if(spec)items.push({id:'q'+(++no),section:'A',marks:fmt.A[i],skill:s.id,spec});
 }
 const typed=s=>{for(let k=0;k<6;k++)if(C.generate(s.id,2,r).kind!=='choice')return true;return false;};
 for(const s of mix(calc.filter(typed),calcReview.filter(typed),fmt.B)){let spec;for(let k=0;k<10;k++){spec=C.generate(s.id,2+Math.floor(r()*2),r);if(spec.kind!=='choice')break;}items.push({id:'q'+(++no),section:'B',marks:2,skill:s.id,spec});}
 const nC=fmt.C.length,fromMain=draw(wpMain,Math.min(nC,wpMain.length)),cs=[...fromMain,...draw(wpReview.length?wpReview:wpMain.length?wpMain:calc,nC-fromMain.length)];
 for(const [i,s] of cs.entries()){const tier=fmt.C[i]>=4?3:2,spec=C.generate(s.id,tier,r);if(spec.wordProblem)spec.vis='';items.push({id:'q'+(++no),section:'C',marks:fmt.C[i],skill:s.id,spec});}
 const max=items.reduce((n,x)=>n+x.marks,0);
 return {id:'paper-'+uid(r),cp:cp.id,title:cp.title,style:cp.style,createdAt:now,minutes:fmt.minutes,max,items,complete:false};
}
// Marking: exact answers earn full marks. An equal fraction that is not in
// simplest form earns 1 of 2 marks, as schools usually deduct a mark for it.
function markItem(item,response){
 const s=item.spec;let correct=false,earned=0,display='',tag=null;
 if(response==null||response===''){return {correct:false,earned:0,display:'(no answer)',tag:'blank'};}
 if(s.kind==='choice'){correct=response===s.ans;display=String(response);}
 else if(s.kind==='key'){
  const t=String(response).trim();display=s.money?'$'+t:t;
  if(!/^\d+(\.\d{1,3})?$/.test(t))return {correct:false,earned:0,display,tag:'format'};
  const v=s.money?Math.round(parseFloat(t)*100):parseFloat(t);correct=s.dec||s.money?Math.abs(v-s.ans)<1e-6:v===s.ans;
 }else if(s.kind==='parts'){
  const res=C.checkParts(s,typeof response==='string'?JSON.parse(response||'{}'):response);correct=res.correct;display=res.display;tag=res.tag||null;
  if(!correct&&res.tag==='form-simplest'&&item.marks>=2)return {correct:false,earned:item.marks-1,display,tag};
 }
 earned=correct?item.marks:0;return {correct,earned,display,tag};
}
function score(paper,skills,{now=Date.now()}={}){
 const items=paper.items.map(it=>{const m=markItem(it,it.response);const sk=skills.find(s=>s.id===it.skill);return {...it,...m,topic:sk?.topic||'',skillName:sk?.name||it.skill,qtext:it.spec.qtext,answer:it.spec.kind==='choice'?it.spec.ans:it.spec.ansText||(it.spec.money?'$'+(it.spec.ans/100).toFixed(2):String(it.spec.ans)),solution:it.spec.fact};});
 const sections=['A','B','C'].map(id=>{const xs=items.filter(i=>i.section===id);return {id,earned:xs.reduce((n,i)=>n+i.earned,0),max:xs.reduce((n,i)=>n+i.marks,0),count:xs.length};}).filter(s=>s.count);
 const topics={};for(const i of items){const t=topics[i.topic]||(topics[i.topic]={topic:i.topic,earned:0,max:0});t.earned+=i.earned;t.max+=i.marks;}
 const total=items.reduce((n,i)=>n+i.earned,0),max=items.reduce((n,i)=>n+i.marks,0),pct=max?total/max:0;
 const band=pct>=.85?'Ready':pct>=.7?'Nearly there':pct>=.5?'Building':'Needs more time';
 const missed=[...new Set(items.filter(i=>i.earned<i.marks).map(i=>i.skillName))];
 const recs=[];
 const sec=id=>sections.find(s=>s.id===id),pc=s=>s&&s.max?s.earned/s.max:null;
 if(pc(sec('C'))!==null&&pc(sec('C'))<.6)recs.push('Word problems (Section C) were the weakest part. Each daily session will now include 3 word problems until the next checkpoint. Ask Hana to draw a bar model before calculating.');
 if(pc(sec('A'))!==null&&pc(sec('A'))<.7)recs.push('Multiple choice slips in Section A suggest checking each option against the question. Encourage working on paper even for multiple choice.');
 if(pc(sec('B'))!==null&&pc(sec('B'))<.7)recs.push('Short-answer accuracy (Section B) needs work: the skills missed here are moved to the front of review.');
 if(items.some(i=>i.tag==='form-simplest'))recs.push('Some fractions were correct but not in simplest form. In Singapore papers this usually costs a mark.');
 if(missed.length)recs.push(`Review first: ${missed.slice(0,6).join(', ')}${missed.length>6?' and others':''}.`);
 if(pct<.5)recs.push('Below 50%: sessions now include extra review of earlier units. Consider repeating this checkpoint in two weeks.');
 if(pct>=.85)recs.push('Strong result. Keep the planned pace.');
 if(paper.elapsedMs&&paper.minutes&&paper.elapsedMs>paper.minutes*60000*1.5)recs.push(`It took ${Math.round(paper.elapsedMs/60000)} minutes against about ${paper.minutes} in school. Speed comes with fluency; timed practice can start once accuracy is steady.`);
 return {...paper,items,sections,topics:Object.values(topics),score:total,max,pct,band,recs,at:paper.at||now,complete:true,updatedAt:now};
}
// Compact record for storage and sync (questions are regenerated never; the
// stored text is what Hana saw).
function record(scored){
 return {id:scored.id,cp:scored.cp,title:scored.title,style:scored.style,at:scored.at,startedAt:scored.createdAt,updatedAt:scored.updatedAt,elapsedMs:scored.elapsedMs||null,minutes:scored.minutes,complete:true,score:scored.score,max:scored.max,pct:scored.pct,band:scored.band,recs:scored.recs,sections:scored.sections,topics:scored.topics,
  items:scored.items.map(i=>({id:i.id,section:i.section,marks:i.marks,earned:i.earned,correct:i.correct,skill:i.skill,skillName:i.skillName,topic:i.topic,qtext:i.qtext,answer:i.answer,response:i.display,tag:i.tag,solution:i.solution,working:i.working||null}))};
}
const api={FORMATS,build,toChoice,markItem,score,record};
if(node)module.exports=api;else root.HanaPapers=api;
})(typeof window==='undefined'?globalThis:window);
