/* Parent view uses the same whitelist payload as exported and mirrored reviews. */
(function(){
'use strict';
const $=id=>document.getElementById(id),R=HanaReview,L=HanaLearning,C=HanaCurriculum,esc=C.esc;
const dialog=document.createElement('dialog');dialog.id='progressDialog';dialog.className='studio-dialog progress-dialog';dialog.setAttribute('aria-labelledby','progressTitle');
dialog.innerHTML=`<div class="dialog-head"><h2 id="progressTitle">Hana’s progress.</h2><button class="btn" id="closeProgress" aria-label="Close progress">×</button></div><p class="map-note">Independent work, help and later recall — so you can choose the next useful step.</p><div id="progressBody"></div><div class="report-actions"><button class="btn" id="downloadReview">Download learning review (JSON)</button><button class="btn" id="downloadCSV">Download answers (CSV)</button></div><p class="map-note">To review progress together, upload the JSON in our chat. These files contain her answers and working. Full game backup is still in Mum &amp; Dad’s settings.</p><details id="mirrorSettings"><summary>Optional private Drive mirror</summary><p>Use a separate Hana relay from the setup instructions in this repository. Euna’s relay is not compatible. Reports stay on this device until you configure this or download them.</p><label for="mirrorURL">Hana Apps Script URL</label><input id="mirrorURL" type="url" autocomplete="off" placeholder="https://script.google.com/macros/s/…/exec"><label for="mirrorSecret">Mirror secret (24+ characters)</label><input id="mirrorSecret" type="password" autocomplete="new-password"><div class="report-actions"><button class="btn" id="saveMirror">Save &amp; send review</button><button class="btn" id="clearMirror">Disconnect mirror</button></div><p id="mirrorStatus" role="status"></p></details>`;
document.body.append(dialog);
function snapshot(){return R.build(HanaStudio.getLearning(),C.skills);}
function metric(label,v){return `<article class="report-period"><h3>${label}</h3><strong>${v.independent}</strong> independent <span class="muted">/ ${v.completed} completed</span><p>${v.supported} with support · ${v.guessed} guessed · ${v.revealed} solutions shown · ${v.repeated} familiar · ${v.manual} for review</p><p>${v.recall} later recalls · ${v.transfer} applications · ${v.lessonChecks} lesson checks</p><small>${(v.activeMs/60000).toFixed(1)} active minutes estimated${v.unmeasured?` · time unknown for ${v.unmeasured} older answers`:''}</small></article>`;}
function drawing(strokes){if(!strokes?.length)return '';return `<svg class="report-drawing" viewBox="0 0 600 220" role="img" aria-label="Hana’s saved working"><rect width="600" height="220" fill="white"/>${strokes.map(s=>`<polyline fill="none" stroke="#55317e" stroke-width="2.5" points="${s.map(p=>p[0]*600+','+p[1]*220).join(' ')}"/>`).join('')}</svg>`;}
function render(){const b=snapshot(),s=b.learning,date=at=>new Date(at).toLocaleString(undefined,{timeZone:b.timeZone});
 $('progressBody').innerHTML=`<p class="map-note">Report date: ${esc(R.day(b.exportedAt,b.timeZone))} · ${esc(b.timeZone)}. Last 7 days includes today. Counts describe different questions and levels; they are not a like-for-like test score.</p><div class="report-periods">${metric('Today',b.periods.today)}${metric('Last 7 days',b.periods.last7)}${metric('Previous 7 days',b.periods.previous7)}</div><h3>Next useful steps</h3>${b.next.filter(Boolean).map(n=>`<div class="report-next"><strong>P${n.year} · ${esc(n.name)} · level ${n.tier}</strong><p>${esc(n.reason)}</p><button class="btn" data-practise="${n.skill}" data-grade="${n.year}">Practise this skill</button></div>`).join('')}<details><summary>All skills &amp; review dates</summary><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Skill</th><th>Evidence</th><th>Next review</th></tr></thead><tbody>${b.skills.map(x=>`<tr><td>P${x.year} · ${esc(x.name)}</td><td>${x.manual?'Grown-up checks needed':`${esc(x.status)} · ${x.independentRecent}/${x.recent} recent independent · level ${x.tier}`}</td><td>${x.manual?'Paper and review':x.reviewAt?(x.due?'Ready now':esc(R.day(x.reviewAt,b.timeZone))):'Learn first'}</td></tr>`).join('')}</tbody></table></div></details><details><summary>Recent answers &amp; working (${Math.min(50,s.events.length)} of ${s.events.length})</summary>${s.events.slice(-50).reverse().map(e=>`<details class="answer-review"><summary>${esc(C.skills.find(x=>x.id===e.skill)?.name||e.skill)} · ${esc(R.category(e))} · ${esc(date(e.at))}</summary><p>${esc(e.question||'Question not recorded')}</p><p><strong>Expected:</strong> ${esc(String(e.answerDisplay??e.answer??'Manual review'))} · Level ${e.tier} · ${esc(e.phase||'Phase not recorded')}</p><p><strong>Hana’s answers:</strong> ${e.attempts?.length?e.attempts.map(a=>esc(String(a.display??a.response))+(a.correct?' ✓':' — retry')).join(' → '):'Not recorded in older builds, or solution shown without an answer.'}</p><p>Confidence: ${esc(e.confidence||'unreported')} · Felt tricky: ${esc(e.obstacle||'not reported')} · ${e.hints||0} hints · ${e.tries||0} retries${e.lessonHelp?' · lesson replayed':''}</p>${Object.entries(e.notes||{}).map(([k,v])=>`<p><strong>${esc(k)}:</strong> ${esc(v)}</p>`).join('')}${drawing(e.strokes)}</details>`).join('')||'<p>No completed questions yet.</p>'}</details><details><summary>What this report can tell us</summary><ul>${b.limits.map(v=>`<li>${esc(v)}</li>`).join('')}</ul><p>Supported answers trigger a smaller step or recap. Three independent answers at the current level increase difficulty. Daily sessions can repair a prerequisite; later recall is tried before a lesson. Changed application questions are available for ${HanaCoach.transferSkills.length} skills. Other skills use varied practice and later recall. Optional reflections do not lower a score, and written notes are not automatically judged.</p></details>`;
 $('progressBody').querySelectorAll('[data-practise]').forEach(btn=>btn.onclick=()=>{dialog.close();document.querySelector(`[data-year="${btn.dataset.grade}"]`).click();HanaStudio.start('focus',btn.dataset.practise);});
 window.HanaMirror?.showSettings();
}
function download(content,type,suffix){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=`hana-learning-${R.day(Date.now())}.${suffix}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('openProgress').onclick=()=>{$('moreDialog').close();render();dialog.showModal();};$('closeProgress').onclick=()=>dialog.close();
$('downloadReview').onclick=()=>download(JSON.stringify(snapshot(),null,2),'application/json','json');$('downloadCSV').onclick=()=>download(R.csv(snapshot()),'text/csv;charset=utf-8','csv');
window.addEventListener('hana:learning-changed',()=>{if(dialog.open)render();});
window.HanaProgress={snapshot,render};
})();
