const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../curriculum.js'),E=require('../exam-style.js'),K=require('../coach.js'),P=require('../papers.js'),Course=require('../course.js'),L=require('../learning.js'),R=require('../learning-review.js');
const random=seed=>()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;};
const near=(a,b,label)=>assert.ok(Math.abs(a-b)<1e-7,`${label}: ${a} vs ${b}`);
const value=q=>q.kind==='parts'?(q.layout==='clock'?q.expect.h*60+q.expect.m:q.expect.N/q.expect.D):q.ans;
// Check conservation, inverse substitutions and boundary conditions rather
// than simply calling the generator's answer formula a second time.
function verify(q){
 const d=q.data,x=value(q);
 switch(q.family){
 case 'regrouped-place': near(d.t===2?x:d.thousands*1000+x*100+d.ones,d.total,q.family);break;
 case 'digit-constraints': {
  const s=String(x);assert.deepEqual([...s].sort(),d.digits.map(String).sort());assert.notEqual(s[0],'0');
  if(d.even)assert.equal(x%2,0);
  // All alternative permutations, generated by inserting digits iteratively.
  let options=[''];for(const n of d.digits)options=options.flatMap(s=>Array.from({length:s.length+1},(_,i)=>s.slice(0,i)+n+s.slice(i)));
  const valid=options.filter(s=>s[0]!=='0'&&(!d.even||Number(s)%2===0)).map(Number);
  assert.ok(valid.every(n=>d.small?x<=n:x>=n));break;
 }
 case 'missing-calculation': near(d.t===2?d.a+x:x-d.a,d.t===2?d.total:d.b+d.x,q.family);break;
 case 'reverse-remainder': if(d.t===2){assert.equal(Math.floor(x/d.divisor),d.quotient);assert.equal(x%d.divisor,d.r);}else{assert.equal((d.N+x)%d.divisor,0);assert.ok(x>0&&x<d.divisor);}break;
 case 'equal-packs': near(d.t===2?x*d.a+d.spare:x/d.b,d.t===2?d.total:d.per,q.family);break;
 case 'missing-fraction': near(d.t===2?d.a/d.D+x:d.a/d.D+x+d.b/d.D,d.t===2?d.total/d.D:1,q.family);break;
 case 'comparison-chain': near(d.t===2?x-d.first:x+d.first-d.gap,d.t===2?d.first-d.gap:d.total,q.family);break;
 case 'shopping-change': near(d.t===2?x+d.count*d.price+d.other:d.count*x+d.other+d.change,d.paid,q.family);break;
 case 'measure-repacking': near(d.t===2?d.count*d.each+x:d.count*x+d.left,d.w*d.k+d.r,q.family);break;
 case 'time-with-break': near(d.t===2?d.start+x+d.pause:x+d.first+d.pause+d.second,d.end,q.family);break;
 case 'rectangle-context': near(d.t===2?x+d.gate:x+d.l*d.w,d.t===2?2*d.L+2*d.W:d.L*d.W,q.family);break;
 case 'graph-reasoning': near(d.t===2?x:x+d.v.reduce((a,b)=>a+b,0),d.t===2?d.v[0]+d.v[2]:d.target,q.family);assert.ok(d.v.every(v=>v%d.scale===0));break;
 case 'rounding-boundary': assert.equal(Math.round(x/d.unit)*d.unit,d.rounded);assert.notEqual(Math.round((x+(d.small?-1:1))/d.unit)*d.unit,d.rounded);break;
 case 'common-multiple-context': assert.equal(x%d.a,0);assert.equal(x%d.b,0);if(d.t===2){for(let k=1;k<x;k++)assert.ok(k%d.a||k%d.b);}else{assert.ok(x>d.low&&x<d.high);assert.equal(Array.from({length:d.high-d.low-1},(_,i)=>d.low+i+1).filter(v=>v%d.a===0&&v%d.b===0).length,1);}break;
 case 'fraction-reverse-set': near(d.t===2?x-x*d.n/d.d:x-x*d.n/d.d*2,d.known,q.family);assert.equal(x%d.d,0);break;
 case 'fraction-servings': if(d.t===2){assert.ok(x*d.d>=d.people&&(x-1)*d.d<d.people);}else near(x+d.people/d.d,d.pizzas,q.family);break;
 case 'two-fractions-whole': {const whole=x*d.d/d.b;near(whole* d.a/d.d+x+d.left,whole,q.family);assert.equal(whole%d.d,0);break;}
 case 'decimal-boundary': if(d.t===2)near(x,Math.round(d.source/10)/10,q.family);else{const cents=Math.round(x*100);assert.equal(Math.floor((cents+5)/10),d.rounded/10);assert.notEqual(Math.floor((cents+(d.small?-1:1)+5)/10),d.rounded/10);}break;
 case 'decimal-repacking': near((d.t===2?x:x/d.needed)*d.bags,d.total/100,q.family);break;
 case 'decimal-compute-round': near(x,Math.round((d.a+d.b)/d.scale)*d.scale/100,q.family);break;
 case 'decimal-total-difference': near(x*100+(d.total-d.long),d.long,q.family);break;
 case 'equal-bundle-difference': {const base=x/d.buy,drink=(d.bill1-base)/d.n;near(base+(d.n+d.extra)*drink,d.bill2,q.family);assert.ok(drink>0&&base>0);break;}
 case 'decimal-change-units': near(x*100-d.gap,d.k*(x*100-d.used),q.family);assert.ok(x*100>d.used);break;
 case 'same-start-change': if(d.t===2)near(x/100,(x/100-d.spent)*d.k,q.family);else near(d.total-x+d.gift,d.k*(x-d.gift),q.family);break;
 case 'two-excesses': {const pupils=d.t===2?x:(x-d.small)/d.b,total=d.t===2?pupils*d.a+d.large:x;near(total-pupils*d.a,d.large,q.family);near(total-pupils*d.b,d.small,q.family);assert.ok(Number.isInteger(pupils)&&pupils>0);break;}
 case 'joined-rectangles': near(x,d.t===2?d.W*d.H+d.a*d.b:d.W+(d.H-d.b)+d.a+d.b+(d.W+d.a)+d.H,q.family);assert.ok(d.b<d.H);assert.ok(q.vis&&q.essentialVisual);break;
 case 'dimension-chain': {const length=d.t===2?d.L:d.L+d.increase;near(2*(length+x/length),d.perimeter,q.family);assert.ok(x>0);break;}
 case 'rectangle-angle': assert.equal(x+d.a+d.b,90);assert.ok(x>0&&x<90);break;
 case 'two-way-table': near(d.t===2?x+d.a:x+d.d+d.row,d.t===2?d.row:d.total,q.family);assert.ok(q.vis.includes('<table'));break;
 default:assert.fail('No independent checker for '+q.family);
 }
}
function response(q){if(q.kind==='key')return q.money?(q.ans/100).toFixed(2):String(q.ans);if(q.kind==='choice')return q.ans;const e=q.expect;if(q.layout==='clock')return {h:e.h,m:e.m};if(q.layout==='units')return {a:e.a,b:e.b};if(q.layout==='remainder')return {q:e.q,r:e.r};const w=Math.floor(e.N/e.D),n=e.N%e.D;return n?{w:w||'',n,d:e.D}:{w};}
test('29 new families across 37 existing skills: independent maths and grading checks',()=>{
 let count=0;
 for(const f of E.families)for(const id of f.skills)for(const t of f.tiers)for(let seed=1;seed<=180;seed++){
  const q=E.generate(id,t,random(seed*997+t),f.id);verify(q);count++;
  assert.equal(q.family,f.id);assert.equal(q.tier,t);assert.equal(q.year,Number(id[1]));assert.equal(q.bankRevision,'h19');
  assert.ok(q.help&&q.fact&&q.steps.length);assert.ok(!/undefined|NaN|Infinity/.test(q.qtext+q.fact+q.vis));
  if(q.kind==='key'){assert.ok(q.ans>=0&&Number.isFinite(q.ans));if(!q.dec)assert.ok(Number.isInteger(q.ans));}
  assert.equal(P.markItem({spec:q,marks:2},response(q)).correct,true,q.qtext);
  if(q.kind==='key')assert.equal(P.markItem({spec:q,marks:2},String(Number(response(q))+1)).correct,false,q.qtext);
  if(id==='p3-fracops'){
   const denominators=[...q.qtext.matchAll(/\d+\/(\d+)/g)].map(m=>+m[1]);assert.ok(denominators.every(d=>d<=12));
   if(denominators.length===2)assert.ok(denominators[0]%denominators[1]===0||denominators[1]%denominators[0]===0,q.qtext);
   assert.ok(value(q)>0&&value(q)<1);
  }
 }
 console.log('Verified',count,'new question instances, their solutions and accepted answer formats.');
 assert.equal(E.families.length,29);assert.equal(new Set(E.families.flatMap(f=>f.skills)).size,37);
});
test('foundation levels stay intact; normal practice and applications use the new bank at the same year/tier',()=>{
 for(const id of new Set(E.families.flatMap(f=>f.skills))){
  assert.equal(E.generate(id,1),null);
  let rich=0,classic=0;
  for(let seed=1;seed<=200;seed++){
   assert.equal(C.generate(id,1,random(seed)).family,undefined);
   const q=C.generate(id,3,random(seed*997));if(q.family){rich++;verify(q);}else classic++;
   assert.equal(q.year,Number(id[1]));assert.equal(q.tier,3);
  }
  assert.ok(rich>100&&classic>10,id+' keeps both reasoning and calculation');
  const app=K.transfer(C,id,3,random(37));assert.ok(app?.family,id);assert.equal(app.tier,3);verify(app);
 }
 assert.equal(K.hasTransfer('p4-wpdecimal',1),false,'new applications cannot claim basic practice as transfer');
});
test('checkpoint papers include new questions, keep essential diagrams and remain fully answerable',()=>{
 let count=0,diagrams=0;
 for(const cp of Course.CHECKPOINTS)for(let seed=1;seed<=24;seed++){
  const paper=P.build(cp.id,C.skills,{random:random(seed*773)});
  assert.equal(paper.max,cp.size==='full'?54:35);
  for(const item of paper.items){const q=item.spec;item.response=response(q);if(q.family)count++;if(q.essentialVisual){assert.ok(q.vis);diagrams++;}if(q.choices)assert.equal(new Set(q.choices.map(o=>o.v)).size,q.choices.length);}
  const scored=P.score(paper,C.skills);assert.equal(scored.score,scored.max);
  const record=P.record(scored);assert.equal(record.items.filter(i=>i.family).length,paper.items.filter(i=>i.spec.family).length);
 }
 assert.ok(count>500&&diagrams>20);
});
test('specific mistakes get useful feedback and supported answers lower challenge; report keeps bank provenance',()=>{
 const q=E.generate('p3-remainder',3,random(8),'reverse-remainder');
 const feedback=K.feedback(q,q.data.r);assert.equal(feedback.tag,'remainder-meaning');assert.ok(!feedback.message.includes(String(q.ans)+' counters'));
 const event={id:'h19-fixture',skill:q.skill,year:q.year,tier:3,at:Date.now(),correct:true,independent:false,tries:2,form:q.form,family:q.family,bankRevision:q.bankRevision};
 assert.equal(L.evidence({events:[event]},q.skill).tier,2);assert.equal(L.evidence({events:[event]},q.skill).secure,false);
 const out=R.build({events:[event]},C.skills).learning.events[0];assert.equal(out.family,q.family);assert.equal(out.bankRevision,'h19');
});
test('new families produce different forms without treating number changes as a new method',()=>{
 const a=E.generate('p4-wpdecimal',3,random(1),'equal-bundle-difference'),b=E.generate('p4-wpdecimal',3,random(2),'equal-bundle-difference'),c=E.generate('p4-wpdecimal',3,random(1),'decimal-change-units');
 assert.equal(a.form,b.form);assert.notEqual(a.signature,b.signature);assert.notEqual(a.form,c.form);
});
