const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const Core=require('../nightly-priority-core.js'),N=require('../nightly-plan.js'),C=require('../curriculum.js'),L=require('../learning.js'),K=require('../course.js'),R=require('../learning-review.js');
const NOW=Date.parse('2026-10-08T12:00:00Z'),DAY=86400000,copy=x=>JSON.parse(JSON.stringify(x));
const catalog={maths:id=>C.skills.some(s=>s.id===id&&!s.manual)};
function plan(){return {schema:1,id:'hana-nightly-2026-10-08',revision:1,student:'Hana',timeZone:'America/Chicago',reviewedDate:'2026-10-07',sessionDate:'2026-10-08',generatedAt:'2026-10-08T05:10:00Z',sourceExportedAt:'2026-10-08T01:00:00Z',subjects:{maths:{focus:'Think about number patterns.',skills:['p3-patterns']}}};}
const storage=()=>{const m=new Map();return {m,getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};};
function env(opts={}){let now=NOW,c={url:'https://script.google.com/macros/s/SYNTHETIC/exec',secret:'synthetic-secret-at-least-24-chars'},p=plan(),response=null;const s=opts.storage||storage(),requests=[];
 const client=Core.create({student:'Hana',catalog,config:()=>c,storage:s,key:'test_hana',hash:async t=>crypto.createHash('sha256').update(t).digest('hex'),now:()=>now,online:()=>opts.online!==false,request:async(u,o)=>{requests.push({u,o});if(opts.request)return opts.request(u,o);return response||{ok:true,type:'cors',text:async()=>JSON.stringify({ok:true,service:'family-learning-mirror',planApi:1,student:'Hana',plan:p})};},...opts.core});
 return {client,s,requests,setPlan:x=>p=x,setResponse:x=>response=x,setNow:x=>now=x,setConfig:x=>c=x,getConfig:()=>copy(c)};
}
test('valid plan uses real curriculum; invalid identity, content, timezone, dates, sources and controls are rejected',()=>{
 assert.deepEqual(Core.validate(plan(),'Hana',catalog,NOW),plan());
 const changes=[p=>p.student='Jonah',p=>p.timeZone='UTC',p=>p.revision=0,p=>p.sessionDate='2026-02-30',p=>p.generatedAt='2026-10-09T00:00:00Z',p=>p.sourceExportedAt='2026-10-05T00:00:00Z',p=>p.sourceExportedAt='2026-10-08T06:00:00Z',p=>p.subjects.maths.skills=['not-a-skill'],p=>p.subjects.maths.skills=['p3-place','p3-place'],p=>p.subjects.maths.focus='<script>',p=>p.subjects.maths.answers=[],p=>p.subjects.science={},p=>delete p.subjects.maths,p=>p.script='x'];
 for(const mutate of changes){const p=plan();mutate(p);assert.throws(()=>Core.validate(p,'Hana',catalog,NOW));}
});
test('Chicago local day handles midnight and both DST transitions',()=>{assert.equal(Core.day(Date.parse('2026-10-08T04:59:59Z')),'2026-10-07');assert.equal(Core.day(Date.parse('2026-10-08T05:00:00Z')),'2026-10-08');for(const t of ['2026-11-01T06:59:59Z','2026-11-01T07:00:00Z'])assert.equal(Core.day(Date.parse(t)),'2026-11-01');for(const t of ['2026-03-08T07:59:59Z','2026-03-08T08:00:00Z'])assert.equal(Core.day(Date.parse(t)),'2026-03-08');});
test('confirmed POST receives but does not adopt until a boundary; secrets never enter cache or receipt',async()=>{const e=env();await e.client.initialize();assert(await e.client.refresh(true));assert.equal(e.client.plan(),null);assert(e.client.report().received);const body=JSON.parse(e.requests[0].o.body);assert.deepEqual(Object.keys(body),['action','secret']);assert.equal(body.action,'readHanaNextSession');assert.equal(e.requests[0].o.credentials,'omit');assert(!e.requests[0].u.includes(body.secret));assert.equal(e.client.adopt().student,'Hana');assert.equal(e.client.report().active.startedAt,null);e.client.started(Core.identity(plan()));assert(e.client.report().active.startedAt);assert(!JSON.stringify([...e.s.m,...Object.entries(e.client.report())]).includes(body.secret));});
test('duplicates preserve receipt/use timestamps; older and conflicting revisions do not replace active work',async()=>{const e=env();await e.client.refresh(true);e.client.adopt();e.client.started(Core.identity(plan()));const first=e.client.report().active; e.setNow(NOW+1000);await e.client.refresh(true);e.client.adopt();assert.deepEqual(e.client.report().active,first);const p=plan();p.subjects.maths.skills=['p3-place'];e.setPlan(p);assert.equal(await e.client.refresh(true),false);assert.equal(e.client.plan().subjects.maths.skills[0],'p3-patterns');p.revision=2;e.setPlan(p);assert(await e.client.refresh(true));assert.equal(e.client.plan().revision,1);assert.equal(e.client.adopt().revision,2);e.setPlan(plan());assert.equal(await e.client.refresh(true),false);assert.equal(e.client.plan().revision,2);});
test('future plan does not displace today and expires by Chicago date; same-date cache works offline after restart',async()=>{const e=env();await e.client.refresh(true);e.client.adopt();const p=plan();p.id='hana-nightly-2026-10-09';p.sessionDate='2026-10-09';e.setPlan(p);await e.client.refresh(true);assert.equal(e.client.adopt().sessionDate,'2026-10-08');const offline=env({storage:e.s,online:false});await offline.client.initialize();assert.equal(offline.client.adopt().sessionDate,'2026-10-08');offline.setNow(NOW+DAY);assert.equal(offline.client.plan(),null);assert.equal(offline.client.adopt().sessionDate,'2026-10-09');offline.setNow(NOW+2*DAY);assert.equal(offline.client.adopt(),null);});
for(const kind of ['opaque','http','html','old-relay','wrong-child','oversized','missing'])test('failure '+kind+' keeps built-in fallback and never reports receipt',async()=>{const e=env();const body={ok:true,service:'family-learning-mirror',planApi:1,student:'Hana',plan:plan()};if(kind==='old-relay')body.service='old';if(kind==='wrong-child')body.student='Jonah';if(kind==='missing')body.ok=false;e.setResponse({ok:kind!=='http',type:kind==='opaque'?'opaque':'cors',text:async()=>kind==='html'?'<html>sign in':kind==='oversized'?'x'.repeat(24001):JSON.stringify(body)});assert.equal(await e.client.refresh(true),false);assert.equal(e.client.report().received,null);assert.equal(e.client.adopt(),null);});
test('disconnect and changed credentials immediately block stale plan; in-flight old connection cannot populate new cache',async()=>{let resolve;const e=env({request:()=>new Promise(r=>resolve=r)});const p=e.client.refresh(true);await new Promise(r=>setImmediate(r));e.setConfig({});e.client.invalidate();resolve({ok:true,type:'cors',text:async()=>JSON.stringify({ok:true,service:'family-learning-mirror',planApi:1,student:'Hana',plan:plan()})});assert.equal(await p,false);assert.equal(e.client.adopt(),null);assert.equal(e.client.report().received,null);});
test('timeout resolves fallback even when a transport ignores abort',async()=>{let tick;const e=env({request:()=>new Promise(()=>{}),core:{setTimer:fn=>(tick=fn,1),clearTimer:()=>{}}});const p=e.client.refresh(true);await new Promise(r=>setImmediate(r));tick();assert.equal(await p,false);assert.equal(e.client.report().received,null);});
test('Hana priorities actually change ordinary focus slots and retain length, word problems, reviews and state',()=>{const s=L.clean(null),base=K.plan(s,C.skills,NOW),before=JSON.stringify(s),out=N.prioritize(base,plan(),s,C.skills,K,L,NOW);assert.equal(out.queue.length,base.queue.length);assert(out.nightlySlots.length>0);assert.equal(out.queue[out.nightlySlots[0]],'p3-patterns');base.queue.forEach((id,i)=>{if(!out.nightlySlots.includes(i))assert.equal(out.queue[i],id);});assert.equal(JSON.stringify(s),before);assert.deepEqual(out.wordProblems,base.wordProblems);assert.deepEqual(out.reviews,base.reviews);});
test('locked topics do not skip course; priorities honor prerequisites, protect due slots, and stop after three daily questions across revisions',()=>{const s=L.clean(null),base=K.plan(s,C.skills,NOW),p=plan();p.subjects.maths.skills=['p4-decimal'];assert.deepEqual(N.prioritize(base,p,s,C.skills,K,L,NOW).queue,base.queue);p.subjects.maths.skills=['p3-muldiv'];const out=N.prioritize({...base,unit:K.UNITS.at(-1).id},p,s,C.skills,K,L,NOW);assert.notEqual(out.queue[0],'p3-muldiv');assert.deepEqual(N.prioritize(base,plan(),s,C.skills,K,{...L,evidence:()=>({due:true})},NOW).queue,base.queue);s.events=Array.from({length:3},(_,i)=>({id:'q'+i,skill:'p3-patterns',tier:1,at:NOW,nightlyPlan:Core.identity(plan())}));const revised=plan();revised.revision=2;assert.deepEqual(N.prioritize(base,revised,s,C.skills,K,L,NOW).queue,base.queue);});
test('plan provenance survives learning merge and review allowlist without altering independence',()=>{const e={id:'synthetic',skill:'p3-patterns',tier:1,at:NOW,correct:true,independent:true,hints:1,nightlyPlan:{...Core.identity(plan()),secret:'must-not-escape'}};const s=L.merge(null,{events:[e]});const b=R.build(s,C.skills,{now:NOW,timeZone:'America/Chicago'});assert.deepEqual(b.learning.events[0].nightlyPlan,Core.identity(plan()));assert.equal(b.learning.events[0].independent,false);assert(!JSON.stringify(b).includes('must-not-escape'));});
module.exports={plan,env};
